V1/62 create poll
kayoumido/HEIGVD-PRO-A-11 pull request #164
Opened 2020-05-19 04:16 UTC by Lindwing

# How to test
Have an authenticated user with existing presentation owned by him.
The route is `/sondage/:idPresentation/creer`

2020-05-19 06:27 UTC, SundayBraid reviewed
## Test

with the GUI I have test the following

- [x] User can create a poll with choice
- [x] Submit button is disable if a field is empty
- [x] HTTP post request are correctly send **Back end feature aren't merge into this branch**
- [x] Messages are showed to notify of success or failure while the execution

## Questions

What if the poll has more or less than 4 answers (eg. true or false) ?

2020-05-19 17:01 UTC, Lindwing commented
It is not practical to lock with 4 choices. I have changed the component. We can create polls with 2 choices or more. I fixed the maximum to 6.

2020-05-20 06:29 UTC, SundayBraid reviewed
## Test

- [ ] I cannot create empty presentation
**i can submit a empty poll if I don't fill any box**
![image](https://user-images.githubusercontent.com/7882245/82411933-f96f6d80-9a72-11ea-83b5-047180c8ca44.png)

- [x] The form send correct number of post request regarding of the number of choice are display (according that all choice form must be filled)

2020-05-20 10:32 UTC, Lindwing commented
Changed in c2df2d0

2020-05-20 12:03 UTC, fabio10000 requested changes
maybe you should drop the issue of creating choices and leave it to someone else and just make a creation of poll

2020-05-20 12:03 UTC, fabio10000 commented on src/resources/js/components/CreatePoll.vue
> +    />
the number of choices should not be hardcoded

2020-05-20 12:03 UTC, fabio10000 commented on src/resources/js/components/CreatePoll.vue
> +      nbChoice: '',
same here should not be hardcoded

2020-05-20 13:20 UTC, Lindwing commented
I remove the create choice part of the component, I don't know-how make this without hardcoded.

2020-05-20 16:59 UTC, fabio10000 approved these changes

2020-05-21 06:49 UTC, SundayBraid approved these changes
I have re-test the create poll feature with recent change

- [x] User can create a poll
- [x] Submit button is disable if the field is empty
- [x] HTTP post request are correctly send
- [x] Messages are showed to notify of success or failure while the execution

2020-05-21 06:49 UTC, merged