V1/112 64 65 66 poll management
kayoumido/HEIGVD-PRO-A-11 pull request #167
Opened 2020-05-20 16:15 UTC by fabio10000

# Cannot be tested
The delete button cannot be fully tested as a backend route has been removed from develop

2020-05-20 16:46 UTC, SundayBraid reviewed
## Test

**the following field has been tested**
When navigate in poll management view
- [x] as a presenter I can see multiple buttons
- [x] as a normal user I can only see the title of the poll and only polls that are not in draft status
- [x] a form field should appear when click the pencil
- [x] Save icon work correctly
- [x] delete icon work correctly
- [x] Publish button work correctly

2020-05-20 16:55 UTC, SundayBraid approved these changes

2020-05-21 09:02 UTC, Lindwing requested changes
There is a warning if you change the subject of a poll.
![pictureReview167](https://user-images.githubusercontent.com/49392659/82542520-6d347780-9b52-11ea-93a4-fc7f201c4119.PNG)

2020-05-21 09:02 UTC, Lindwing commented on src/resources/js/components/Poll.vue
> +  },
In the console on Firefox, if I click on delete I receive this : TypeError: alert.showMessage is not a function
The reason is there is not .alert at the end like this.$parent.$parent.$parent.parentRef$.alert

2020-05-21 09:02 UTC, Lindwing commented on src/resources/js/components/Polls.vue
> +      const { alert } = this.$parent.$parent.parentRefs;
Same problem here

2020-05-21 09:07 UTC, fabio10000 commented on src/resources/js/components/Polls.vue
> +      const { alert } = this.$parent.$parent.parentRefs;
here is ok because the `{ alert } = xxx.yyy.zzz` is equivalent to `alert = xxx.yyy.zzz.alert`

2020-05-21 09:18 UTC, fabio10000 commented on src/resources/js/components/Poll.vue
> +  },
fixed

2020-05-21 09:27 UTC, Lindwing approved these changes
It is good for me.

2020-05-21 09:27 UTC, merged